<template>
  <!-- <div id="diff" style="width: 400px; height: 970px; overflow-x:hidden; overflow-y:show"></div> -->
  <div id="diff" style="width: 545px; height: 435px; overflow:auto; padding-left:5px"></div>
</template>

<script>

export default {
  name: "diffView",
  data() {
    return {
      diffData: '',
      version1: "",
      version2: "",
      diffs:
        "--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n"
    };
  },
  methods: {
    // 绘制差异视图的函数
    initDiffView() {
      this.version1 = this.$store.state.twoVersion1;
      this.version2 = this.$store.state.twoVersion2;
      this.$axios({
        method: "post",
        url: "/diffDt",
        data: {
          version1: this.version1,
          version2: this.version2
        }
      })
        .then(res => {
          this.diffData = res.data;
          this.drawDiffView(this.diffData);
        })
        .catch(reason => {
          console.log(reason);
        });
    },
    drawDiffView(diffdata) {
            const targetElement = document.getElementById("diff");
            const configuration = {
                inputFormat: "json",
                drawFileList: true, // 绘制文件列表
                fileContentToggle: true, //文件内容可折叠
                fileListStartVisible: true,  // 初始情况下文件列表为展开
                matching: "lines", // 匹配方式
                highlight: true,
                outputFormat: 'line-by-line',
                renderNothingWhenEmpty: true
            };
            const diff2htmlUi = new Diff2HtmlUI(
                targetElement,
                diffdata,
                configuration
            );
            diff2htmlUi.draw();
            diff2htmlUi.highlightCode();
            diff2htmlUi.fileListToggle(false); // true为文件列表默认展开，false为文件列表默认折叠
    }
  }
};
</script>
<style>

.d2h-file-name-wrapper{    
  font-size: 10px;
}
.line-num1{
  width:0.5em
}
.d2h-code-linenumber{
  width:3.5em
}
.d2h-code-line{
  padding-right: 280px;
  padding-left: 30px;
}

#diff{
  border-top: 1px solid #e3e3e3;
  overflow: auto;
}
.d2h-file-collapse, .d2h-file-wrapper{
  border: 0;
}
.d2h-file-wrapper{
  margin-bottom:0.01em
}
.d2h-file-header{
  height:15px
}
.d2h-diff-table{
  font-size: 10px;
}
.d2h-file-collapse{
  font-size: 10px;
}
.line-num1, .line-num2{
  width: 0;
}
.d2h-code-linenumber{
  position: relative;
}
.d2h-diff-table{
  width: 100%;
}
</style>
